-- MySQL Script generated by MySQL Workbench
-- 03/27/17 23:35:26
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `codigo` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PC` (
  `idPC` INT NOT NULL,
  `modelo` VARCHAR(30) NULL,
  `procesador` VARCHAR(45) NULL,
  `ram` VARCHAR(5) NULL,
  `disco_duro` VARCHAR(5) NULL,
  `no_serie` VARCHAR(30) NULL,
  `os` VARCHAR(30) NULL,
  PRIMARY KEY (`idPC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN` (
  `idAdmin` INT NOT NULL,
  `usr_name` VARCHAR(25) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SESION` (
  `idSesion` INT NOT NULL,
  `entrada` TIMESTAMP(20) NULL,
  `salida` TIMESTAMP(20) NULL,
  `Usuario_idUsuario` INT NULL,
  `PC_idPC` INT NOT NULL,
  `Admin_idAdmin` INT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `fk_Sesion_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Sesion_PC1_idx` (`PC_idPC` ASC),
  INDEX `fk_Sesion_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Sesion_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `mydb`.`USUARIO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_PC1`
    FOREIGN KEY (`PC_idPC`)
    REFERENCES `mydb`.`PC` (`idPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `mydb`.`ADMIN` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAGINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAGINA` (
  `idPagina` INT NOT NULL,
  `nombrePagina` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACCESO_PAGINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACCESO_PAGINA` (
  `idAcceso_Pagina` INT NOT NULL,
  `Sesion_idSesion` INT NOT NULL,
  `Pagina_idPagina` INT NOT NULL,
  PRIMARY KEY (`idAcceso_Pagina`),
  INDEX `fk_Acceso_Pagina_Sesion1_idx` (`Sesion_idSesion` ASC),
  INDEX `fk_Acceso_Pagina_Pagina1_idx` (`Pagina_idPagina` ASC),
  CONSTRAINT `fk_Acceso_Pagina_Sesion1`
    FOREIGN KEY (`Sesion_idSesion`)
    REFERENCES `mydb`.`SESION` (`idSesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Acceso_Pagina_Pagina1`
    FOREIGN KEY (`Pagina_idPagina`)
    REFERENCES `mydb`.`PAGINA` (`idPagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
