-- MySQL Script generated by MySQL Workbench
-- 05/11/17 22:33:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema JavaCS_BD
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JavaCS_BD
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JavaCS_BD` DEFAULT CHARACTER SET utf8 ;
USE `JavaCS_BD` ;

-- -----------------------------------------------------
-- Table `JavaCS_BD`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`USUARIO` (
  `codigo` INT NOT NULL,
  `status` TINYINT(1) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`PC` (
  `idPC` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(30) NULL,
  `procesador` VARCHAR(45) NULL,
  `ram` VARCHAR(7) NULL,
  `disco_duro` VARCHAR(7) NULL,
  `no_serie` VARCHAR(30) NULL,
  `os` VARCHAR(30) NULL,
  `mac` VARCHAR(120) NULL,
  `grupo` TINYINT NULL,
  PRIMARY KEY (`idPC`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`ADMIN` (
  `idAdmin` INT NOT NULL AUTO_INCREMENT,
  `usr_name` VARCHAR(25) NOT NULL,
  `pass` VARCHAR(45) NOT NULL,
  `tipo` TINYINT(1) NOT NULL,
  `status` TINYINT(1) NULL,
  PRIMARY KEY (`idAdmin`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`SESION`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`SESION` (
  `idSesion` BIGINT NOT NULL AUTO_INCREMENT,
  `entrada` TIMESTAMP NULL,
  `salida` TIMESTAMP NULL,
  `Usuario_idUsuario` INT NULL,
  `PC_idPC` INT NOT NULL,
  `Admin_idAdmin` INT NULL,
  PRIMARY KEY (`idSesion`),
  INDEX `fk_Sesion_Usuario_idx` (`Usuario_idUsuario` ASC),
  INDEX `fk_Sesion_PC1_idx` (`PC_idPC` ASC),
  INDEX `fk_Sesion_Admin1_idx` (`Admin_idAdmin` ASC),
  CONSTRAINT `fk_Sesion_Usuario`
    FOREIGN KEY (`Usuario_idUsuario`)
    REFERENCES `JavaCS_BD`.`USUARIO` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_PC1`
    FOREIGN KEY (`PC_idPC`)
    REFERENCES `JavaCS_BD`.`PC` (`idPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Sesion_Admin1`
    FOREIGN KEY (`Admin_idAdmin`)
    REFERENCES `JavaCS_BD`.`ADMIN` (`idAdmin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`PAGINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`PAGINA` (
  `idPagina` BIGINT NOT NULL AUTO_INCREMENT,
  `nombrePagina` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`PROGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`PROGRAMA` (
  `idPROGRAMA` INT NOT NULL AUTO_INCREMENT,
  `Nombre` VARCHAR(20) NOT NULL,
  `proceso` VARCHAR(20) NOT NULL,
  `Descripcion` VARCHAR(150) NULL,
  PRIMARY KEY (`idPROGRAMA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`USO_PC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`USO_PC` (
  `idUSO_PC` INT NOT NULL AUTO_INCREMENT,
  `Encendido` TIMESTAMP NOT NULL,
  `apagado` TIMESTAMP NULL,
  `PC_idPC` INT NOT NULL,
  PRIMARY KEY (`idUSO_PC`),
  INDEX `fk_USO_PC_PC1_idx` (`PC_idPC` ASC),
  CONSTRAINT `fk_USO_PC_PC1`
    FOREIGN KEY (`PC_idPC`)
    REFERENCES `JavaCS_BD`.`PC` (`idPC`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`ACCESO_PAGINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`ACCESO_PAGINA` (
  `SESION_idSesion` BIGINT NOT NULL,
  `PAGINA_idPagina` BIGINT NOT NULL,
  INDEX `fk_SESION_has_PAGINA_PAGINA1_idx` (`PAGINA_idPagina` ASC),
  INDEX `fk_SESION_has_PAGINA_SESION1_idx` (`SESION_idSesion` ASC),
  CONSTRAINT `fk_SESION_has_PAGINA_SESION1`
    FOREIGN KEY (`SESION_idSesion`)
    REFERENCES `JavaCS_BD`.`SESION` (`idSesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SESION_has_PAGINA_PAGINA1`
    FOREIGN KEY (`PAGINA_idPagina`)
    REFERENCES `JavaCS_BD`.`PAGINA` (`idPagina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JavaCS_BD`.`USO_PROGRAMA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JavaCS_BD`.`USO_PROGRAMA` (
  `SESION_idSesion` BIGINT NOT NULL,
  `PROGRAMA_idPROGRAMA` INT NOT NULL,
  INDEX `fk_SESION_has_PROGRAMA_PROGRAMA1_idx` (`PROGRAMA_idPROGRAMA` ASC),
  INDEX `fk_SESION_has_PROGRAMA_SESION1_idx` (`SESION_idSesion` ASC),
  CONSTRAINT `fk_SESION_has_PROGRAMA_SESION1`
    FOREIGN KEY (`SESION_idSesion`)
    REFERENCES `JavaCS_BD`.`SESION` (`idSesion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SESION_has_PROGRAMA_PROGRAMA1`
    FOREIGN KEY (`PROGRAMA_idPROGRAMA`)
    REFERENCES `JavaCS_BD`.`PROGRAMA` (`idPROGRAMA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
