/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.awt.Component;
import java.net.InetAddress;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import servidor.OrdenarTareas;

/**
 *
 * @author ARON
 */
public class Panel extends javax.swing.JPanel {

    List<String []> tareas;
    InetAddress ip;
    /**
     * Creates new form prueba
     */
    public Panel(ArrayList<String []> datos,InetAddress ip) {
        initComponents();
        tareas=datos;
        this.ip=ip;
    }
    
public void agregarProcesos(int orden){
        this.removeAll();
        Collections.sort(tareas,new OrdenarTareas(orden));
        for (String[] dato : tareas) {
            this.add(new proceso(dato[3],dato[0],dato[1],dato[2],ip));
        }
        this.updateUI();
        //scroll.updateUI();
    }

    public  void eliminarProceso(Component p){
        this.remove(p);
        this.updateUI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.GridLayout(1, 1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
