/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.net.InetAddress;
import servidor.Ordenes;

/**
 *
 * @author Redes
 */
public class proceso extends javax.swing.JPanel {

    /**
     * Creates new form proceso
     */
    InetAddress ip;
    Ordenes orden=new Ordenes();
    public proceso(String nombre,String nombreImagen,String pid,String memoria,InetAddress ip) {
        initComponents();
        this.titulo.setText(nombre);
        this.nombreImagen.setText(nombreImagen);
        this.memoria.setText(memoria);
        this.pid.setText(pid);
        this.ip=ip;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpOpciones = new javax.swing.JPopupMenu();
        MatarProceso = new javax.swing.JMenuItem();
        titulo = new javax.swing.JLabel();
        nombreImagen = new javax.swing.JLabel();
        pid = new javax.swing.JLabel();
        memoria = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        MatarProceso.setText("jMenuItem1");
        MatarProceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatarProcesoActionPerformed(evt);
            }
        });
        popUpOpciones.add(MatarProceso);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        titulo.setText("Nombre Proceso");

        nombreImagen.setText("proceso.exe");

        pid.setText("1654");

        memoria.setText("302,156 kb");

        jLabel1.setText("PID:");

        jLabel2.setText("nombre:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(memoria))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pid)
                    .addComponent(nombreImagen))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titulo)
                    .addComponent(nombreImagen)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(memoria)
                    .addComponent(jLabel1)
                    .addComponent(pid))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        if(evt.getButton()==3)
        {
            popUpOpciones.show(evt.getComponent(), evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_formMouseClicked

    private void MatarProcesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatarProcesoActionPerformed
        orden.matar(ip,pid.getText());
    }//GEN-LAST:event_MatarProcesoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MatarProceso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel memoria;
    private javax.swing.JLabel nombreImagen;
    private javax.swing.JLabel pid;
    private javax.swing.JPopupMenu popUpOpciones;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
